# Site settings
title: Célia Desgrange
email: celia.desgrange@univ-grenoble-alpes.fr
#email: desgrange@mpia.de
description: > # this means to ignore newlines until "baseurl:"
  I am an observer, imaging exoplanets and disks with various facilities. I have been an European Southern Observatory (ESO) Fellow in Chile on VLT/UT3 since November 2024.
#baseurl: "/urban-theme" # the subpath of your site, e.g. /blog
url: "https://cdesgrange.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  cdesgrange
#avatar: /fig/HD95086_overview.png

# Build settings
markdown: kramdown
permalink: pretty
#<meta name="description" content="Description de ma page" />
