# Site settings
title: Célia Desgrange
email: celia.desgrange@universite-grenoble-alpes.fr
#email: desgrange@mpia.de
description: > # this means to ignore newlines until "baseurl:"
  
  Célia Desgrange's website. Website still in construction.
#baseurl: "/urban-theme" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  cdesgrange
avatar: /fig/HD95086_overview.png

# Build settings
markdown: kramdown
permalink: pretty
