# Site settings
title: Célia Desgrange
email: desgrange@mpia.de or celia.desgrange@univ-grenoble-alpes.fr
#email: desgrange@mpia.de
description: > # this means to ignore newlines until "baseurl:"
  I am a PhD student in high-contrast observations of exoplanets and disks with the instrument VLT/SPHERE at IPAG (Grenoble, France) and MPIA (Heidelberg, Germany).
#baseurl: "/urban-theme" # the subpath of your site, e.g. /blog
url: "https://cdesgrange.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  cdesgrange
#avatar: /fig/HD95086_overview.png

# Build settings
markdown: kramdown
permalink: pretty
#<meta name="description" content="Description de ma page" />
